//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinjureTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public int RetailerId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public int State { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
    
        public virtual Distributor Distributor { get; set; }
    }
}
